version: '3'
services:
  frontend:
    image: gcr.io/singin-386108/test2
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      - watchtower
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30