name: Deploy Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: continuous-deployment
  RUN_REGION: asia-south1

jobs:
  deploy:
    name: Deploying to Google Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Build and push Docker image
        run: gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_ID }}:${{ github.sha }}
        
      
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.5.0

        with:
          services: continuous-deployment-kunjqyu4kq-el
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_ID }}:${{ github.sha }}
          region: ${{ env.RUN_REGION }}
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ env.PROJECT_ID }}