name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY_JSON }}
  RUN_REGION: asia-south1
  APP_ID: continous-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT_KEY
      
      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA
          gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
