name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID}}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  APP_ID: continuous-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY_JSON }}

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file={{ secrets.GCP_SA_KEY_JSON }}
      
      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}//${{ env.APP_ID }}
          gcloud run deploy ${{ env.APP_ID }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_ID }} --platform managed --region asia-south1
