name: Deploy 🚀 Google Cloud Run (☁🏃)
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: continuous-deployment
  RUN_REGION: asia-south1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  deploy:
    name: Deploying to google cloud
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@main
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Building (🏗)
        run: |-
          gcloud builds submit \
            --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      # Setup gcloud CLI
      - name: Deploy (🚀)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: SERVICE_ID
          image: gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA
          region: $RUN_REGION
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: $PROJECT_ID