name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuous-deployment:${{ github.sha }} .

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy continuous-deployment \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuous-deployment:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
