name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: github-action-850@singin-386108.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuous-deployment
        gcloud config set run/region us-central1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy continuous-deployment --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuous-deployment \
        --platform managed \
        --allow-unauthenticated \